kind: Secret
apiVersion: v1
metadata:
  name: traefik-forward-auth-secrets
  namespace: {{ .Values.namespace | default "kube-system" }}
  labels:
    name: traefik
type: Opaque
data:
  CLIENT_SECRET: {{ printf "%s" .Values.deployment.client.secret | b64enc }}
  SECRET: {{ printf "%s" .Values.deployment.secret | b64enc }} 
