version: '3'

services:
  traefik:
    image: traefik
    command: -c /traefik.toml
    # command: -c /traefik.toml --logLevel=DEBUG
    ports:
      - "8085:80"
      - "8086:8080"
    networks:
      - traefik
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: emilevauge/whoami
    networks:
      - traefik
    labels:
      - "traefik.backend=whoami1"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.localhost.com"

  whoami2:
    image: emilevauge/whoami
    networks:
      - traefik
    labels:
      - "traefik.backend=whoami2"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.localhost.org"

  traefik-forward-auth:
    build: ../
    environment:
      - ID_SERVICE=GoogleAuth
      - CLIENT_ID=your-client-id
      - CLIENT_SECRET=your-client-secret
      - SECRET=something-random
      - INSECURE_COOKIE=true
      - COOKIE_DOMAIN=localhost.com
      - AUTH_HOST=auth.localhost.com
    networks:
      - traefik

networks:
  traefik:
