// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	provider "github.com/aliotta/traefik-forward-auth/pkg/provider"
	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// ExchangeCode provides a mock function with given fields: redirectURI, code
func (_m *Provider) ExchangeCode(redirectURI string, code string) (string, error) {
	ret := _m.Called(redirectURI, code)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(redirectURI, code)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(redirectURI, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(redirectURI, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoginURL provides a mock function with given fields: redirectURI, state
func (_m *Provider) GetLoginURL(redirectURI string, state string) string {
	ret := _m.Called(redirectURI, state)

	if len(ret) == 0 {
		panic("no return value specified for GetLoginURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(redirectURI, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUser provides a mock function with given fields: token
func (_m *Provider) GetUser(token string) (provider.User, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 provider.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (provider.User, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) provider.User); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(provider.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with given fields:
func (_m *Provider) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Setup provides a mock function with given fields:
func (_m *Provider) Setup() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
