// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CoreControllerInterface is an autogenerated mock type for the CoreControllerInterface type
type CoreControllerInterface struct {
	mock.Mock
}

// ExchangeAuth0TokenWithCoreSignedJwt provides a mock function with given fields: deploymentId, token
func (_m *CoreControllerInterface) ExchangeAuth0TokenWithCoreSignedJwt(deploymentId string, token string) (string, error) {
	ret := _m.Called(deploymentId, token)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeAuth0TokenWithCoreSignedJwt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(deploymentId, token)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(deploymentId, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(deploymentId, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCoreControllerInterface creates a new instance of CoreControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoreControllerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoreControllerInterface {
	mock := &CoreControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
