// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	logrus "github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"

	provider "github.com/aliotta/traefik-forward-auth/pkg/provider"
)

// ServerInterface is an autogenerated mock type for the ServerInterface type
type ServerInterface struct {
	mock.Mock
}

// AllowHandler provides a mock function with given fields: rule
func (_m *ServerInterface) AllowHandler(rule string) http.HandlerFunc {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for AllowHandler")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(string) http.HandlerFunc); ok {
		r0 = rf(rule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// AuthCallbackHandler provides a mock function with given fields:
func (_m *ServerInterface) AuthCallbackHandler() http.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthCallbackHandler")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func() http.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// AuthHandler provides a mock function with given fields: providerName, rule
func (_m *ServerInterface) AuthHandler(providerName string, rule string) http.HandlerFunc {
	ret := _m.Called(providerName, rule)

	if len(ret) == 0 {
		panic("no return value specified for AuthHandler")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(string, string) http.HandlerFunc); ok {
		r0 = rf(providerName, rule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// LogoutHandler provides a mock function with given fields:
func (_m *ServerInterface) LogoutHandler() http.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogoutHandler")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func() http.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// RootHandler provides a mock function with given fields: w, r
func (_m *ServerInterface) RootHandler(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// authRedirect provides a mock function with given fields: logger, w, r, p
func (_m *ServerInterface) authRedirect(logger *logrus.Entry, w http.ResponseWriter, r *http.Request, p provider.Provider) {
	_m.Called(logger, w, r, p)
}

// buildRoutes provides a mock function with given fields:
func (_m *ServerInterface) buildRoutes() {
	_m.Called()
}

// NewServerInterface creates a new instance of ServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerInterface {
	mock := &ServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
